# Generated by Django 6.0.5 on 2026-05-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_end_time_booking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='denial_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
