# Generated by Django 6.0.5 on 2026-05-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='host_payout_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
