# Generated by Django 6.0.5 on 2026-05-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_servicelisting_latitude_servicelisting_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='pricing_type',
            field=models.CharField(choices=[('per_night', 'Per Night'), ('per_hour', 'Per Hour'), ('per_ride', 'Per Ride'), ('per_person', 'Per Person'), ('per_session', 'Per Session'), ('flat_rate', 'Flat Rate')], default='per_night', max_length=20),
        ),
    ]
