# Generated by Django 6.0.5 on 2026-05-23 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_availability_unique_together_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='cancellation_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='payments.cancellationpolicy'),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Platform fee percentage', max_digits=5),
        ),
    ]
